name: flutter_to_debian
description: A command application to help you easily bundle your flutter app build into a debian package ready for production.
version: 2.0.1
homepage: https://www.hooreo.com/
repository: https://github.com/jeffrey0606/flutter_to_debian

environment:
  sdk: ">=2.15.0 <4.0.0"

executables:
  flutter_to_debian:

dependencies:
  args: ^2.4.2
  mime_type: ^1.0.0
  path: ^1.8.1
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
